In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_csv("diabetes.csv")
print(data.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [3]:
X = data.drop("Outcome", axis=1)
y = data["Outcome"]


In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [6]:
lr_params = {
    "solver": "lbfgs",
    "max_iter": 1000,
    "random_state": 8888,
}

lr = LogisticRegression(**lr_params)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

lr_dict = classification_report(y_test, y_pred_lr, output_dict=True)
lr_dict

Logistic Regression Accuracy: 0.7532467532467533
[[79 20]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



{'0': {'precision': 0.8144329896907216,
  'recall': 0.797979797979798,
  'f1-score': 0.8061224489795918,
  'support': 99.0},
 '1': {'precision': 0.6491228070175439,
  'recall': 0.6727272727272727,
  'f1-score': 0.6607142857142857,
  'support': 55.0},
 'accuracy': 0.7532467532467533,
 'macro avg': {'precision': 0.7317778983541328,
  'recall': 0.7353535353535354,
  'f1-score': 0.7334183673469388,
  'support': 154.0},
 'weighted avg': {'precision': 0.7553936387360154,
  'recall': 0.7532467532467533,
  'f1-score': 0.7541909620991253,
  'support': 154.0}}

In [7]:
knn_params = {
    "n_neighbors": 5,
    "weights": "uniform",
    "metric": "minkowski",
}

knn = KNeighborsClassifier(** knn_params)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))
report_dict = classification_report(y_test, y_pred_knn, output_dict=True)
report_dict

KNN Accuracy: 0.6948051948051948
[[79 20]
 [27 28]]
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        99
           1       0.58      0.51      0.54        55

    accuracy                           0.69       154
   macro avg       0.66      0.65      0.66       154
weighted avg       0.69      0.69      0.69       154



{'0': {'precision': 0.7452830188679245,
  'recall': 0.797979797979798,
  'f1-score': 0.7707317073170732,
  'support': 99.0},
 '1': {'precision': 0.5833333333333334,
  'recall': 0.509090909090909,
  'f1-score': 0.5436893203883495,
  'support': 55.0},
 'accuracy': 0.6948051948051948,
 'macro avg': {'precision': 0.6643081761006289,
  'recall': 0.6535353535353535,
  'f1-score': 0.6572105138527113,
  'support': 154.0},
 'weighted avg': {'precision': 0.6874438454627133,
  'recall': 0.6948051948051948,
  'f1-score': 0.6896451405568147,
  'support': 154.0}}

In [8]:
rf_params = {
    "n_estimators": 100,
    "max_depth": None,
    "min_samples_split": 2,
    "random_state": 8888,
}

rf = RandomForestClassifier(** rf_params)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))
report_dict = classification_report(y_test, y_pred_rf, output_dict=True)
report_dict

Random Forest Accuracy: 0.7272727272727273
[[76 23]
 [19 36]]
              precision    recall  f1-score   support

           0       0.80      0.77      0.78        99
           1       0.61      0.65      0.63        55

    accuracy                           0.73       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.73      0.73      0.73       154



{'0': {'precision': 0.8,
  'recall': 0.7676767676767676,
  'f1-score': 0.7835051546391752,
  'support': 99.0},
 '1': {'precision': 0.6101694915254238,
  'recall': 0.6545454545454545,
  'f1-score': 0.631578947368421,
  'support': 55.0},
 'accuracy': 0.7272727272727273,
 'macro avg': {'precision': 0.7050847457627119,
  'recall': 0.711111111111111,
  'f1-score': 0.7075420510037982,
  'support': 154.0},
 'weighted avg': {'precision': 0.7322033898305086,
  'recall': 0.7272727272727273,
  'f1-score': 0.72924579489962,
  'support': 154.0}}

In [9]:
%pip install setuptools
import mlflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
models = [
    (
        "Logistic Regression",
        LogisticRegression(**lr_params),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "KNN",
        KNeighborsClassifier(**knn_params),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "Random Forest",
        RandomForestClassifier(**rf_params),
        (X_train, y_train),
        (X_test, y_test)
    )
]


In [11]:
reports = []

for model_name, model, train_set, test_set in models:
    X_train = train_set[0]
    y_train = train_set[1]
    X_test = test_set[0]
    y_test = test_set[1]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    reports.append(report)

In [12]:
mlflow.set_experiment("Diabetes Prediction")
mlflow.set_tracking_uri("http://127.0.0.1:5000")

for i, element in enumerate(models):
    model_name = element[0]
    model = element[1]
    report = reports[i]

    with mlflow.start_run(run_name=model_name):
        mlflow.log_param("model", model_name)
        mlflow.log_metric("accuracy", report["accuracy"])
        mlflow.log_metric("recall_class_1", report["1"]["recall"])
        mlflow.log_metric("recall_class_0", report["0"]["recall"])
        mlflow.log_metric("f1_score_macro", report["macro avg"]["f1-score"])
        mlflow.log_params(model.get_params())
        mlflow.sklearn.log_model(model, "model")
        print(f"Logged {model_name} to MLflow")

2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas
2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables
2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types
2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints
2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults
2026/03/14 09:36:09 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments
2026/03/14 09:36:10 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/03/14 09:36:10 INFO mlflow.store.db.utils: Updating database tables
2026/03/14 09:36:10 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/03/14 09:36:10 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2026/03/14 09:36:10 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/03/14 09:36:10 INFO alembic.runtime

MlflowException: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError("HTTPConnection(host='127.0.0.1', port=5000): Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it"))